-- EJECUTAR ESTO EN EL SQL EDITOR DE SUPABASE PARA ARREGLAR LA TABLA DE EMPLEADOS
-- Agregando columnas faltantes a la tabla 'employees'
ALTER TABLE employees ADD COLUMN IF NOT EXISTS cedula TEXT;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS position TEXT;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS contract_type TEXT CHECK (contract_type IN ('Tiempo Definido', 'Tiempo Indefinido'));
ALTER TABLE employees ADD COLUMN IF NOT EXISTS payment_type TEXT CHECK (payment_type IN ('Semanal', 'Quincenal', 'Mensual'));
ALTER TABLE employees ADD COLUMN IF NOT EXISTS exit_date DATE;

-- Asegurar que la tabla 'settlements' exista
CREATE TABLE IF NOT EXISTS settlements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT REFERENCES employees(id) ON DELETE CASCADE,
    aguinaldo_amount DECIMAL(10, 2) NOT NULL,
    cesantia_amount DECIMAL(10, 2) NOT NULL,
    total_amount DECIMAL(10, 2) NOT NULL,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Asegurar que la tabla 'employee_work_logs' sea compatible
ALTER TABLE employee_work_logs ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'paid'));
