-- Tablas para el sistema de Tiento
-- Nota: Ejecutar esto en el SQL Editor de Supabase

-- 1. Usuarios
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    role TEXT CHECK (role IN ('admin', 'waiter')) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Productos
CREATE TABLE IF NOT EXISTS products (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    description TEXT,
    category TEXT,
    media_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Ventas
CREATE TABLE IF NOT EXISTS sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    total_amount DECIMAL(10, 2) NOT NULL,
    payment_method TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    user_id BIGINT REFERENCES users(id)
);

-- 4. Ítems de Venta
CREATE TABLE IF NOT EXISTS sale_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id BIGINT REFERENCES sales(id) ON DELETE CASCADE,
    product_name TEXT NOT NULL,
    quantity INTEGER NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Gastos
CREATE TABLE IF NOT EXISTS expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category TEXT NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    description TEXT,
    date DATE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Empleados
CREATE TABLE IF NOT EXISTS employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    daily_salary DECIMAL(10, 2) NOT NULL,
    hire_date DATE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Registros de Trabajo de Empleados
CREATE TABLE IF NOT EXISTS employee_work_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT REFERENCES employees(id) ON DELETE CASCADE,
    days_worked INTEGER NOT NULL,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    total_payment DECIMAL(10, 2) NOT NULL,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'paid')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Cesantías
CREATE TABLE IF NOT EXISTS cesantias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT REFERENCES employees(id) ON DELETE CASCADE,
    amount DECIMAL(10, 2) NOT NULL,
    date DATE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insertar un usuario admin inicial (usuario: admin, password: admin123)
-- El password ya está hasheado con bcrypt para ser compatible con el backend.
INSERT INTO users (username, password, role) 
VALUES ('admin', '$2b$10$LkO1vjBTzSZk3vokUyPotejClVM4COK5QoQEI/5w5ir2EmSj5M.dW', 'admin')
ON CONFLICT (username) DO NOTHING;
