-- Migration: Add table for individual worked days
-- Run this in Supabase SQL Editor

-- Table to store each worked day individually
CREATE TABLE IF NOT EXISTS employee_worked_days (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT REFERENCES employees(id) ON DELETE CASCADE,
    work_date DATE NOT NULL,
    daily_rate DECIMAL(10, 2) NOT NULL,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'paid')),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(employee_id, work_date)
);

-- Index for faster lookups by employee and date
CREATE INDEX IF NOT EXISTS idx_worked_days_employee ON employee_worked_days(employee_id);
CREATE INDEX IF NOT EXISTS idx_worked_days_date ON employee_worked_days(work_date);

-- Enable RLS
ALTER TABLE employee_worked_days ENABLE ROW LEVEL SECURITY;

-- Policy for admin access
CREATE POLICY "Admin full access to worked days" ON employee_worked_days
    FOR ALL USING (true);
